FROM rust:alpine as builder
WORKDIR /app
COPY . .
RUN apk add --no-cache musl-dev gcc && \
    rustup target add aarch64-unknown-linux-musl && \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=gcc cargo build --target aarch64-unknown-linux-musl --release

FROM scratch
COPY --from=builder /app/target/aarch64-unknown-linux-musl/release/rustyalias /rustyalias
EXPOSE 5053/udp
EXPOSE 5053/tcp
ENV RUST_LOG=info
USER 65534:65534
CMD ["/rustyalias"]